const _UNIT_TYPE_KEY = 'SITE';
const _PRODUCTS_TYPE_KEY = 'SENSORS';
const _TYPE_LAST_EVENT = 'MAINTENANCE';
const _TYPE_RECOMMENDED_EVENT = 'RECOMENDED-MAINTENANCE';
const _FUNC_NAME_STATISTIC = 'GET_STATISTIC';
const _FUNC_API_STATISTIC = '/entity/api/functions/';


enum _CPI_EVENT_LIST  {
    EVENT_ANALYTIC_FILTER = 'analyticFilterEvent',
    PAYPOD_UNIT_SELECTED = 'payPodUnitSelected',
    UPDATE_UNIT_LIST = 'updateUnitList',
    REQUEST_FILTER_UPDATE = 'requestFilterUpdate',
};

export const UNIT_TYPE_KEY = _UNIT_TYPE_KEY;
export const PRODUCTS_TYPE_KEY = _PRODUCTS_TYPE_KEY;
export const TYPE_LAST_EVENT = _TYPE_LAST_EVENT;
export const TYPE_RECOMMENDED_EVENT = _TYPE_RECOMMENDED_EVENT;
export const FUNC_NAME_STATISTIC = _FUNC_NAME_STATISTIC;
export const FUNC_API_STATISTIC = _FUNC_API_STATISTIC;
export const CPI_EVENT_LIST = _CPI_EVENT_LIST;
