import { MenuItem } from './menu.interface';

export function getDefaultMenuList(): MenuItem[] {
    const parent = {
        path: 'administration',
        key: 'administration',
        permission: ['ROUTE.GET_LIST', 'ROLE.GET_LIST', 'ROLE.MATRIX.GET', 'USER.GET_LIST', 'CLIENT.GET_LIST'],
        position: null,
        title: 'global.menu.admin.main',
        icon: 'settings',
        url: ['administration'],
        parent: null,
        children: [],
    };

    return [
        {
            ...parent,
            children: [
                {
                    path: 'dashboard-management',
                    position: 0,
                    permission: 'DASHBOARD.CREATE',
                    url: ['administration', 'dashboard-management'],
                    icon: 'dashboard',
                    title: 'admin-config.common.menu.dashboard-mng',
                    children: [],
                    parent: parent,
                },
                {
                    path: 'specification-management',
                    position: 1,
                    permission: 'DASHBOARD.CREATE',
                    url: ['administration', 'specification-management', 'ui'],
                    icon: 'settings_applications',
                    title: 'admin-config.common.menu.specification-mng',
                    children: [],
                    parent: parent,
                },
                {
                    path: 'gateway',
                    position: 0,
                    permission: 'ROUTE.GET_LIST',
                    url: ['administration', 'gateway'],
                    icon: 'traffic',
                    title: 'global.menu.admin.gateway',
                    children: [],
                    parent: parent,
                },
                {
                    path: 'metrics',
                    position: 1,
                    permission: 'ROUTE.GET_LIST',
                    url: ['administration', 'metrics'],
                    icon: 'network_check',
                    title: 'global.menu.admin.metrics',
                    children: [],
                    parent: null,
                },
                {
                    path: 'health',
                    position: 2,
                    permission: 'ROUTE.GET_LIST',
                    url: ['administration', 'health'],
                    icon: 'network_check',
                    title: 'global.menu.admin.health',
                    children: [],
                    parent: parent,
                },
                {
                    path: 'roles-management',
                    position: 3,
                    permission: 'ROLE.GET_LIST',
                    url: ['administration', 'roles-management'],
                    icon: 'supervisor_account',
                    title: 'global.menu.admin.rolesManagement',
                    children: [],
                    parent: parent,
                },
                {
                    path: 'roles-matrix',
                    position: 4,
                    permission: 'ROLE.MATRIX.GET',
                    url: ['administration', 'roles-matrix'],
                    icon: 'view_comfy',
                    title: 'global.menu.admin.rolesMatrix',
                    children: [],
                    parent: parent,
                },
                {
                    path: 'user-management',
                    position: 5,
                    permission: 'USER.GET_LIST',
                    url: ['administration', 'user-management'],
                    icon: 'supervisor_account',
                    title: 'global.menu.admin.userManagement',
                    children: [],
                    parent: parent,
                },
                {
                    path: 'client-management',
                    position: 6,
                    permission: 'CLIENT.GET_LIST',
                    url: ['administration', 'client-management'],
                    icon: 'account_circle',
                    title: 'global.menu.admin.clientManagement',
                    children: [],
                    parent: parent,
                },
                {
                    path: 'audits',
                    position: 7,
                    permission: '',
                    url: ['administration','audits'],
                    icon: 'track_changes',
                    title: 'global.menu.admin.audits',
                    children: [],
                    parent: parent,
                },
                {
                    path: 'logs',
                    position: 8,
                    permission: '',
                    url: ['administration', 'logs'],
                    icon: 'list',
                    title: 'global.menu.admin.logs',
                    children: [],
                    parent: parent,
                },
                {
                    path: 'form-playground',
                    position: 9,
                    permission: 'ROUTE.GET_LIST',
                    url: ['administration', 'form-playground'],
                    icon: 'content_paste',
                    title: 'global.menu.admin.formPlayground',
                    children: [],
                    parent: parent,
                },
                {
                    path: 'maintenance',
                    position: 10,
                    permission: ['ELASTICSEARCH.INDEX', 'CONFIG.ADMIN.REFRESH', 'CONFIG.CLIENT.REFRESH'],
                    url: ['administration', 'maintenance'],
                    icon: 'M',
                    title: 'global.menu.admin.maintenance',
                    children: [],
                    parent: parent,
                },
                {
                    path: 'translation',
                    position: 11,
                    permission: '',
                    url: ['administration', 'translation'],
                    icon: 'translate',
                    title: 'global.menu.admin.translation',
                    children: [],
                    parent: parent,
                },
                {
                    path: 'docs',
                    position: 12,
                    permission: 'ROUTE.GET_LIST',
                    url: ['administration', 'docs'],
                    icon: 'A',
                    title: 'global.menu.admin.apidocs',
                    children: [],
                    parent: parent,
                },
            ],
        },
    ];
}
