version: '3.3'
services:
    web-app:
        image: xmonline/xm-webapp:${IMAGE_XM_WEBAPP_TAG:-latest}
        networks:
            - xm2
        environment:
            - GATE_HOST=gate-app
        ports:
            - 80:80
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        logging:
            driver: syslog
            options:
                tag: web-app
                syslog-facility: local7
    test:
      image: trion/ng-cli-karma:15.0.3
      volumes:
        - ../:/app
      command:
        - /bin/sh
        - -c
        - ls && export NODE_OPTIONS="--max-old-space-size=8192" && npm run test:prod

networks:
    xm2:
        driver: overlay

