import {
    booleanElastic,
    containsElastic,
    customFieldElastic,
    dateElastic,
    elasticQueryChips,
    entityElastic,
    entitySelectElastic,
    multiElastic,
    multiSelectElastic,
    nestedPropElastic,
    strictNumberElastic,
    strictNumberOrContainsStringElastic,
    strictStringElastic, templateElastic, userDelegationElastic,
    userFullnameElastic
} from './xm-table-filter-elastic';

export const TABLE_FILTERS_ELASTIC = {
    default: containsElastic,
    nestedProp: nestedPropElastic,
    index: containsElastic,
    number: containsElastic,
    link: strictNumberOrContainsStringElastic,
    date: dateElastic,
    dateArray: null,
    image: null,
    currency: containsElastic,
    boolean: booleanElastic,
    strictNumber: strictNumberElastic,
    entity: entityElastic,
    entitySelect: entitySelectElastic,
    enum: strictStringElastic,
    stateKey: containsElastic,
    multiElastic: multiElastic,
    multiSelectElastic: multiSelectElastic,
    typeKey: containsElastic,
    user: strictStringElastic,
    jsonpath: null,
    userFullname: userFullnameElastic,
    action: null,
    customField: customFieldElastic,
    template: templateElastic,
    userDelegation: userDelegationElastic,
    select: strictStringElastic,
    linkCategory: containsElastic,
    chips: elasticQueryChips,
    '': containsElastic,
};
