name: test-ui

on:
  pull_request:
    branches-ignore:
      - main
    types:
      - labeled


jobs:
  test:
    if: ${{ github.event.label.name == 'ci-cd-trigger' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '18.10.0'

      - name: Install dependencies and test
        run: |
          npm install
          npm run lint
          npm run test:prod

      - name: Test finish
        run : echo "Test Finished Successfully!"
